title: <p align="center"> Bhaskar M </p>
logo: /assets/img/Capture.png

description:
  <p align="center">
   
  <br>   
I am working as a Bi tester for 3.5 years
  <br>
  </p>



theme: jekyll-theme-minimal
